### ISSUE TITLE
Mockup Entrada y Salida de Datos

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-kem#2]
https://www.figma.com/proto/kOYcbfpIjU6Un3uhNmQfcy/Untitled?type=design&t=0WbBuSr93CwKAoGW-0&scaling=min-zoom&page-id=0%3A1&node-id=9-6&starting-point-node-id=9%3A6

REPORTE DE MOKUP

[REPORTE DEL MOCKUP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-kem/files/14313601/REPORTE.DEL.MOCKUP.pdf)

visual stude 
[SistemaEntradaSalida.zip](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-kem/files/14316199/SistemaEntradaSalida.zip)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by josealfredo79** [comment]
Bien hecho y revisado...la calificacion es de 19.4
